---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Overall survival analysis

The aim of this notebook is to show how to draw a **Kaplan-Meier curve** for the overall survival analysis of the cohort of my dissertation.

**Loading packages:**
```{r}
library(openxlsx)
library(survival)
library(survminer)
```

**Reading data file:**
```{r}
# defining data file path
data_path <- "C:/Users/Ana/Documents/GitHub/dissertation/data/data_survival/overall_survival.xlsx"

# reading data file
data <- read.xlsx(data_path)
head(data)
```

**Drawing survival curves:**
```{r}
## overall survival
fit_k <- survfit(Surv(Survival.months, Status) ~ 1, data = data)
ggsurvplot(fit_k, data = data, censor.shape = "|", censor.size = 3,
           xlim = c(0,250),
           pval = FALSE,
           risk.table = TRUE,
           legend.title = "",
           xlab = "Time (months)",
           #palette = c("red","darkblue"),
           legend.labs = 'GIST Overall Survival',
           #pval.coord = c(25,0.92),
           risk.table.y.text = FALSE
           #title = "Overall Suvival"
)
```

```{r}
## overall survival Fletcher
fit_k <- survfit(Surv(Survival.months, Status) ~ Fletcher, data = data)
ggsurvplot(fit_k, data = data, censor.shape = "|", censor.size = 3,
           xlim = c(0,250),
           pval = TRUE,
           risk.table = TRUE,
           legend.title = "",
           xlab = "Time (months)",
           #palette = c("red","darkblue"),
           #legend.labs = c("High", "Low","Moderate","Very low"),
           pval.coord = c(10,0.1),
           risk.table.y.text = FALSE
           #title = "Overall Suvival"
)
```

```{r}
fit_k <- survfit(Surv(Survival.months, Status) ~ Alteration, data = data)
ggsurvplot(fit_k, data = data, censor.shape = "|", censor.size = 3,
           xlim = c(0,250),
           pval = TRUE,
           risk.table = TRUE,
           legend.title = "",
           xlab = "Time (months)",
           #palette = c( "darkblue", "black", "red"),
           #legend.labs = c("KIT", "KIT/PDGFRA WT","PDGFRA"),
           pval.coord = c(10,0.1),
           risk.table.y.text = FALSE
           #title = "Overall Suvival"
)
```